# docker-compose.yml (Refactored for modern Docker Compose)
# Orchestrates the DGM application and the Ollama LLM service.

services:
  dgm-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dgm_app
    depends_on:
      - ollama
    volumes:
      - .:/dgm
    restart: on-failure

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data:
    # This named volume persists the downloaded LLM models
